// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List        = require("bs-platform/lib/js/list.js");
var React       = require("react");
var Random      = require("bs-platform/lib/js/random.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Page");

Random.self_init(/* () */0);

var messages = /* :: */[
  "Nah.",
  /* :: */[
    "Nope.",
    /* :: */[
      "Not even close.",
      /* :: */[
        "Not yet.",
        /* :: */[
          "No.",
          /* :: */[
            "Don't even ask...",
            /* :: */[
              "\":)\"",
              /* :: */[
                "Don't bother to look outside",
                /* :: */[
                  "Possibly a tiny bit of sunshine? Nah.",
                  /* :: */[
                    "Maybe tomorrow?",
                    /* :: */[
                      "Keep your hopes up!",
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var message = List.nth(messages, Random.$$int(List.length(messages)));

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("article", {
                  className: "summer-info"
                }, React.createElement("div", {
                      className: "summer-info__inner"
                    }, React.createElement("h1", {
                          className: "hero-question-heading"
                        }, "Is it summer in Sweden yet?"), React.createElement("p", undefined, message)));
    });
  return newrecord;
}

exports.component = component;
exports.messages  = messages;
exports.message   = message;
exports.make      = make;
/* component Not a pure module */
